{{ if .Values.tls.manageCert }}
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    meta.helm.sh/release-name: {{ $.Release.Name }}
    meta.helm.sh/release-namespace: {{ $.Release.Namespace }}
  labels: {{ include "keycloak.labels" . | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
spec:
  dnsNames: {{ include "keycloak.dnsNames" . | nindent 4 }}
  secretName: {{ include "keycloak.secretName" . }}
  issuerRef:
    name: {{ .Values.tls.issuerRef.name | required "A valid issuerRef.name is required!" }}
    kind: {{ default "ClusterIssuer" .Values.tls.issuerRef.kind }}
  duration: {{ .Values.tls.duration }}
{{ end }}
