---

apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ $.Release.Name }}-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    meta.helm.sh/release-name: {{ $.Release.Name }}
    meta.helm.sh/release-namespace: {{ $.Release.Namespace }}
  labels: {{ include "keycloak.labels" . | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
spec:
  hostname:
    {{- if .Values.hostname.admin }}
    admin: {{ .Values.hostname.admin -}}
    {{ end }}
    {{- if .Values.hostname.adminUrl }}
    adminUrl: {{ .Values.hostname.adminUrl -}}
    {{ end }}
    hostname: {{ required ".Values.hostname.hostname is required" .Values.hostname.hostname }}
  db:
    usernameSecret:
      name: {{ .Values.database.credentials.secret }}
      key: {{ .Values.database.credentials.usernameKey }}
    passwordSecret:
      name: {{ .Values.database.credentials.secret }}
      key: {{ .Values.database.credentials.passwordKey }}
    port: {{ .Values.database.connection.port }}
    schema: {{ .Values.database.connection.schema }}
    vendor: {{ .Values.database.connection.vendor }}
    host: {{ .Values.database.connection.host }}
    database: {{ .Values.database.name }}
    {{- include "keycloak.poolingconfig" . | nindent 4 }}
  instances: {{ .Values.instances }}
  tlsSecret: {{ include "keycloak.secretName" . | required ".Values.tls.secretName is required!" }}
  image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
