# Keycloak hostname configuration
hostname:
  # The hostname for accessing the administration console.
  admin:
  # The base URL for accessing the administration console, including scheme, host, port and path
  adminUrl:
  # Hostname for the Keycloak server, required.
  hostname:

# Keycloak database configuration
database:
  # The name of the database
  name:
  # Database credentials
  credentials:
    # The secret to load the database username and password from.
    secret:
    # The key containing the username in the secret.
    usernameKey: DB_USER
    # The key containing the password in the secret.
    passwordKey: DB_PASS
  # Database connection details
  connection:
    # The database vendor, e.g. postgres.
    vendor: postgres
    # The schema for the database, e.g. postgresql
    schema: postgresql
    # The host of the database server
    host:
    # The port of the database server
    port: 5432
    # Database connection pooling configuration
    poolingconfig:
      # The minimum size of the connection pool
      poolMinSize:
      # The initial size of the connection pool
      poolInitialSize:
      # The max size of the connection pool
      poolMaxSize:

# Image configuration
image:
  # The name of the image
  name: keycloak/keycloak
  # The image repository
  repo: quay.io
  # The image tag
  tag: 22.0

# How many instances of Keycloak to deploy
instances: 1
# What secret to use for TLS
tls:
  # The name of the secret to use
  secretName:
  manageCert: false
  issuerRef:
    name:
    kind:
  duration: "30d"

nameOverride:
fullnameOverride:
